Änderungen Profil /löschen/pw ändern
schulzi66/mebli pull request #27
Opened 2022-04-15 17:31 UTC by IlkaL

Hier sind die Änderungen zum Profil löschen. Funktioniert noch nicht ganz wegen der Reauthentifizierungsanforderung von Firebase. Würde wie du siehst dieses über die Eingabe des alten PW realisieren bei pw ändern. Die E-Mail haben wir ja immer. Wenn dieser Ansatz nicht gut ist, bitte bescheid geben.

2022-04-17 13:19 UTC, schulzi66 requested changes

2022-04-17 13:19 UTC, schulzi66 commented on libs/profile/src/lib/components/profile/profile.component.html
> +            Das Password muss diese Anforderungen erfüllen: </div>
Keine nicht übersetzten Texte im Template

2022-04-17 13:19 UTC, schulzi66 commented on libs/profile/src/lib/components/profile/profile.component.html
> +            (click)="close({oldPassword: oldpassword.value},{newPassword: newpassword.value})">
Hier gibst du zwar das alte Passwort mit in die "onChangePassword()" Methode in der profile.component.ts mit, aber dort sind nicht die entsprechenden Anpassungen gemacht (siehe Zeile 30 in profile.component.ts) heißt es geschieht nichts damit.

2022-04-17 13:19 UTC, schulzi66 commented on libs/profile/src/lib/components/profile/profile.component.html
> +           type="oldpassword"
type ist der Typ des Inputs. Diese sind fest definierte Werte, um beispielsweise automatisch bei type="password" den Input als sternchen darzustellen. Heißt "oldpassword" und "newpassword" klappt nicht

2022-04-17 13:19 UTC, schulzi66 commented on libs/profile/src/lib/components/profile/profile.component.html
> +            Das Password muss diese Anforderungen erfüllen: </div>
Außerdem sind hier keine Anforderungen aufgelistet, die das Password erfüllen muss

2022-04-17 13:19 UTC, schulzi66 commented on libs/profile/src/lib/components/profile/profile.component.html
> +            Das Password muss diese Anforderungen erfüllen: </div>
Auf kleinen Handys passt auch das Styling nicht

2022-04-17 13:19 UTC, schulzi66 commented on libs/profile/src/lib/components/profile/profile.component.html
> +            Das Password muss diese Anforderungen erfüllen: </div>
![image](https://user-images.githubusercontent.com/9035340/163715690-ac47a4fe-dcbb-46b9-952d-61e1c1c43ea8.png)

2022-04-17 13:19 UTC, schulzi66 commented on libs/auth/src/lib/services/auth.service.ts
> +    public async deleteProfil()
Rechtschreibfehler: deleteProfile()

2022-04-17 13:19 UTC, schulzi66 commented on libs/auth/src/lib/services/auth.service.ts
>              user.updatePassword(newPassword);
Hier wird es nötig sein, folgendes aufzurufen
user.reauthenticateWithCredential(EmailAuthProvider.credential(user.email, oldPassword));

Dies geht zumindest nur soweit ich das sehe bei nicht Google User. Müsste man sich genauer anschauen

2022-04-17 13:19 UTC, schulzi66 commented on libs/auth/src/lib/services/auth.service.ts
> +            if (user.getIdToken !== null)
Klappt das?

2022-04-17 13:19 UTC, schulzi66 commented on libs/auth/src/lib/services/auth.service.ts
> +        console.log("user delete ");
Hier sollte wenn der User gelöscht wird, auf die Startseite navigiert werden

2022-05-05 20:56 UTC, schulzi66 requested changes
Habe noch schnell die Formatierung nachgezogen. Ansonsten ein Paar Anmerkungen und EdgeCases die mir beim Testen aufgefallen sind

2022-05-05 20:56 UTC, schulzi66 commented on libs/profile/src/lib/components/profile/profile.component.ts
> +        await this.authService.deleteProfile('gmail');
Wofür sendest du hier den string 'gmail' mit?

2022-05-05 20:56 UTC, schulzi66 commented on libs/profile/src/lib/components/profile/profile.component.ts
> +                    this.authService.deleteProfile(result.data.confPassword);
Nachdem man sich erneut mit google eingeloggt hat, bleibt das Popup bestehen und im Hintergrund navigiert er schon auf die Login Seite. (siehe Bild) 
![image](https://user-images.githubusercontent.com/9035340/167022489-8ec8e4d6-89a3-482e-9710-efe74abc4e5b.png)

2022-05-05 20:56 UTC, schulzi66 commented on libs/auth/src/lib/services/auth.service.ts
> +                    await this.storeProfileData({
Wir müssen nicht die ProfilDaten des User erneut speichern, wenn er sich gerade löschen will

2022-05-05 20:56 UTC, schulzi66 commented on libs/profile/src/lib/components/profile/profile.component.html
> +        <button class="w-full p-3 my-1 text-center border border-blue-500 rounded-lg focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-blue-300"
Mir ist aufgefallen, dass man hier ein Passwort wählen kann, was nicht unseren Passwort Richtlinien entspricht

2022-05-05 20:56 UTC, schulzi66 commented on libs/auth/src/lib/services/auth.service.ts
> +            if (user.getIdToken !== null) console.log('user id: ' + user.uid);
Die Logs bitte noch löschen

2022-05-05 20:56 UTC, schulzi66 commented on libs/profile/src/lib/components/profile/profile.component.ts
> +                if (result.data.confPassword != null) {
Meistens will man bei Javascript/Typescript Vergleiche mit === bzw. !== ausführen (siehe https://stackoverflow.com/questions/523643/difference-between-and-in-javascript)

Unabhängig davon schlägt die Logik hier fehl, wenn man ein leeres Passwort eingibt. Heißt der Fall des leeren Strings muss auch noch überprüft werden

2022-05-05 20:56 UTC, schulzi66 commented on libs/auth/src/lib/services/auth.service.ts
> +                await reauthenticateWithCredential(user, EmailAuthProvider.credential(user.email, confPassword));
Wenn hier etwas fehlschlägt, weil z.B. das Passwort falsch war was der User eingegeben hat, bekommt der normale User es nicht mit

2022-05-08 10:59 UTC, IlkaL commented on libs/profile/src/lib/components/profile/profile.component.html
> +        <button class="w-full p-3 my-1 text-center border border-blue-500 rounded-lg focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-blue-300"
Das würde ich nach dem mergen einfügen. Da dieses feature ja schon im main branch bei der Regestrierung vorhanden ist:)

2022-05-08 14:26 UTC, IlkaL commented on libs/profile/src/lib/components/profile/profile.component.ts
> +        await this.authService.deleteProfile('gmail');
hab es rausgenommen.

2022-05-08 19:20 UTC, IlkaL commented on libs/auth/src/lib/services/auth.service.ts
> +                await reauthenticateWithCredential(user, EmailAuthProvider.credential(user.email, confPassword));
habe versucht es einzubauen. Leider passt die Reihenfolge der Codeabhandlung nicht. Siehe 2ten push

2022-05-09 18:34 UTC, schulzi66 approved these changes

2022-05-09 20:26 UTC, merged